-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public.usuario
(
    id_usuario SERIAL PRIMARY KEY,
    nome character varying(90) NOT NULL,
    email character varying(150) NOT NULL UNIQUE,
    senha TEXT NOT NULL,
    data_cadastro DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS public.titulo
(
    id_titulo SERIAL PRIMARY KEY,
    nome character varying(100) NOT NULL,
    genero character varying(50) NOT NULL,
    tipo character varying(20) NOT NULL,
    ano_lancamento INTEGER NOT NULL,
    sinopse TEXT,

    CONSTRAINT chk_tipo
        CHECK (tipo IN ('Filme', 'Serie')),

    CONSTRAINT chk_ano_lancamento
        CHECK (ano_lancamento >= 1888)
);

CREATE TABLE IF NOT EXISTS public.avaliacao
(
    id_avaliacao SERIAL PRIMARY KEY,
    nota INTEGER NOT NULL,
    comentario TEXT,
    data_avaliacao DATE NOT NULL DEFAULT CURRENT_DATE,
    id_titulo INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,

    CONSTRAINT chk_nota
        CHECK (nota BETWEEN 1 AND 5),

    CONSTRAINT fk_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES public.usuario (id_usuario)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_titulo
        FOREIGN KEY (id_titulo)
        REFERENCES public.titulo (id_titulo)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT unique_usuario_titulo
        UNIQUE (id_usuario, id_titulo)
);

END;


INSERT INTO public.usuario (nome, email, senha)
VALUES
('João Silva', 'joao@email.com', '123456'),
('Maria Souza', 'maria@email.com', '654321'),
('Carlos Oliveira', 'carlos@email.com', 'abc123'),
('Ana Santos', 'ana@email.com', 'senha123'),
('Pedro Costa', 'pedro@email.com', 'pedro456');


INSERT INTO public.titulo (nome, genero, tipo, ano_lancamento, sinopse)
VALUES
('Interestelar', 'Ficção Científica', 'Filme', 2014,
 'Um grupo de astronautas viaja pelo espaço em busca de um novo lar para a humanidade.'),

('O Senhor dos Anéis', 'Fantasia', 'Filme', 2001,
 'Um jovem recebe a missão de destruir um poderoso anel antes que ele caia nas mãos do mal.'),

('Homem-Aranha: Sem Volta Para Casa', 'Ação', 'Filme', 2021,
 'Peter Parker enfrenta as consequências de ter sua identidade revelada.'),

('Stranger Things', 'Ficção Científica', 'Serie', 2016,
 'Um grupo de jovens enfrenta acontecimentos sobrenaturais em uma pequena cidade.'),

('Breaking Bad', 'Drama', 'Serie', 2008,
 'Um professor de química começa a produzir drogas para garantir o futuro de sua família.'),

('The Last of Us', 'Drama', 'Serie', 2023,
 'Duas pessoas atravessam os Estados Unidos em um mundo devastado por uma pandemia.');


INSERT INTO public.avaliacao
(nota, comentario, data_avaliacao, id_titulo, id_usuario)
VALUES
(5, 'Filme excelente, com uma história muito boa.', '2026-09-20', 1, 1),
(5, 'Um dos melhores filmes de fantasia.', '2026-09-21', 2, 1),
(4, 'Muito divertido e cheio de ação.', '2026-09-22', 3, 2),
(5, 'Série muito interessante e envolvente.', '2026-09-22', 4, 2),
(5, 'História excelente e personagens muito bons.', '2026-09-23', 5, 3),
(4, 'Gostei bastante da série.', '2026-09-23', 6, 3),
(5, 'Um filme que vale muito a pena assistir.', '2026-09-24', 1, 4),
(4, 'Muito bom, principalmente os efeitos visuais.', '2026-09-24', 3, 5),
(5, 'Uma das melhores séries que já assisti.', '2026-09-25', 4, 4),
(5, 'Excelente desenvolvimento da história.', '2026-09-25', 5, 5);


SELECT
    u.nome AS usuario,
    t.nome AS titulo,
    t.tipo,
    a.nota,
    a.comentario,
    a.data_avaliacao
FROM public.avaliacao AS a
INNER JOIN public.usuario AS u
    ON a.id_usuario = u.id_usuario
INNER JOIN public.titulo AS t
    ON a.id_titulo = t.id_titulo
ORDER BY a.id_avaliacao;